# Generated by Django 4.2.7 on 2023-11-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0063_remove_product_reviewer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('product',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
