# Generated by Django 4.2.7 on 2023-11-25 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0009_alter_shoppingcart_img_alter_shoppingcart_price_and_more'),
        ('main_page', '0064_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='product',
            name='cart_prods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shopping_cart.shoppingcart'),
        ),
    ]
