# Generated by Django 4.2.7 on 2023-11-25 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0009_alter_shoppingcart_img_alter_shoppingcart_price_and_more'),
        ('main_page', '0065_alter_review_options_alter_product_cart_prods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cart_prods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.shoppingcart'),
        ),
    ]
