# Generated by Django 4.2.7 on 2023-11-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0067_alter_review_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('👍 (За)', 'Голос за'), ('👎 (Против)', 'Голос против')], max_length=200, null=True, verbose_name='Голос'),
        ),
    ]
